refresh_rate: 1 seconds

appenders:
  stdout:
    kind: console
    encoder:
      kind: pattern
      pattern: "{h({d(%H:%M:%S)})} - {m}{n}"
  
  log_file:
    kind: rolling_file
    append: true
    path: "log/log.log"
    encoder:
      pattern: "{h({d(%m-%d-%Y %H:%M:%S)})} - {m}{n}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 10mb
      roller:
        kind: fixed_window
        base: 1
        count: 100
        pattern: "log/log{}.log"
root:
  level: info
  appenders:
    - stdout
    - log_file

loggers:
  app::backend::db:
    level: error
  app::requests:
    level: info
    appenders:
      - requests
    additive: false